CREATE table IF NOT exists categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_categories PRIMARY KEY (id)
);


CREATE table IF NOT exists users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);


CREATE TABLE IF NOT exists notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255) NOT NULL,
   message VARCHAR(255) NOT NULL,
   image_url VARCHAR(255),
   date TIMESTAMP WITHOUT TIME ZONE,
   category_id BIGINT,
   CONSTRAINT pk_notifications PRIMARY KEY (id)
);
ALTER TABLE notifications ADD CONSTRAINT FK_NOTIFICATIONS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);


CREATE table IF NOT exists subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   token VARCHAR(255) NOT NULL,
   user_id BIGINT,
   CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);
ALTER TABLE subscriptions ADD CONSTRAINT uc_subscriptions_token UNIQUE (token);
ALTER TABLE subscriptions ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


CREATE table IF NOT exists users_inscribed_categories (
	user_id int8 NOT NULL,
	inscribed_categories_id int8 NOT NULL,
	CONSTRAINT fka9cs7xdmwvy9nl80wvv2eulkb FOREIGN KEY (inscribed_categories_id) REFERENCES categories(id),
	CONSTRAINT fkkudl6u1j9kgutap7on03f921l FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE table IF NOT exists users_allow_to_send_notification (
	user_id int8 NOT NULL,
	allow_to_send_notification_id int8 NOT NULL,
	CONSTRAINT fk7riy6eckuwxfmtp8fp8lw18fi FOREIGN KEY (allow_to_send_notification_id) REFERENCES categories(id),
	CONSTRAINT fkoo126nr7w878h8o069w12b4pm FOREIGN KEY (user_id) REFERENCES users(id)
);
