CREATE table IF NOT exists categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_categories PRIMARY KEY (id)
);


CREATE table IF NOT exists users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);


CREATE TABLE IF NOT exists notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255) NOT NULL,
   message VARCHAR(255) NOT NULL,
   image_url VARCHAR(255),
   date TIMESTAMP WITHOUT TIME ZONE,
   category_id BIGINT,
   CONSTRAINT pk_notifications PRIMARY KEY (id)
);
ALTER TABLE notifications ADD CONSTRAINT FK_NOTIFICATIONS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);


CREATE table IF NOT exists subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   token VARCHAR(255) NOT NULL,
   user_id BIGINT,
   CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);
ALTER TABLE subscriptions ADD CONSTRAINT uc_subscriptions_token UNIQUE (token);
ALTER TABLE subscriptions ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


CREATE table IF NOT exists users_category (
	user_id int8 NOT NULL,
	category_id int8 NOT NULL
);
ALTER TABLE public.users_category ADD CONSTRAINT fkdydsp05ralpwbvr6egtx9q11p FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.users_category ADD CONSTRAINT fklvu6ubxyoywr544e84pjxy2mr FOREIGN KEY (category_id) REFERENCES categories(id);